wm_kwargs:
  h_dim: 2048                 # 8d
  rssm_hidden: 256             # d
  classes: 16                  # d/16
  enc_depth: 16                # d/16
  dec_depth: 16                # d/16
  units: 256                   # d
 
ac_kwargs:
  units: 256                   # d