wm_kwargs:
  h_dim: 3072                 # 8d
  rssm_hidden: 384             # d
  classes: 24                  # d/16
  enc_depth: 24                # d/16
  dec_depth: 24                # d/16
  units: 384                   # d
 
ac_kwargs:
  units: 384                   # d