wm_kwargs:
  h_dim: 4096                 # 8d
  rssm_hidden: 512             # d
  classes: 32                  # d/16
  enc_depth: 32                # d/16
  dec_depth: 32                # d/16
  units: 512                   # d
 
ac_kwargs:
  units: 512                   # d